### PR TITLE
Gitignore template

### PR DESCRIPTION
**Pull request by code-kot**
You can add a ".gitignore.template" file to the program's folder to copy it into the new repository instead of creating new file every time.

### CODE REVIEW

**Comment by frogonwheels** [comment]
Great idea.. but why is this two commits?  I'm thrilled that you're using TCGit and contributing back.. but could you please reformat this as a single commit.

**Comment by code-kot** [comment]
Done. I'm new in git =)

**Comment by frogonwheels** [comment]
Thankyou.  Writing this program was my baptism by fire into git.   I'm so happy to be away from Team Coherence.

**Comment by code-kot** [comment]
You are welcome 😊 Your program helps very much to us.

**Pull request merged**
